1.5

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -77,8 +77,8 @@ jobs:
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
-      - name: Fail if Quality Gate fails
-        if: steps.qualitygate.outputs.quality_gate_status != 'PASSED'
-        run: |
-          echo "❌ Merge blocked: Quality Gate failed in SonarQube!"
-          exit 1
+      # - name: Fail if Quality Gate fails
+      #   if: steps.qualitygate.outputs.quality_gate_status != 'PASSED'
+      #   run: |
+      #     echo "❌ Merge blocked: Quality Gate failed in SonarQube!"
+      #     exit 1
